id: I2F1C9193
legacy_id: P000438
ocr_import_info:
  bdrc_scan_id: W00KG03976
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T00:27:41'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T13:43:04.316804+00:00'
last_modified: 2022-08-30 21:44:55.597917
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG03976
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00KG03976
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། འཇིགས་མེད་ཕུན་ཚོགས་འབྱུང་གནས།
  author: མཁན་པོ་འཇིགས་ཕུན།
statistics:
  ocr_word_mean_confidence_index: 0.9648930047679068
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I00KG03978:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03978
      total_pages: 175
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG03978.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9554370607696822
    legacy_id: v001
  I00KG03980:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03980
      total_pages: 220
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I00KG03980.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9650754116260288
    legacy_id: v003
  I00KG03979:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03979
      total_pages: 176
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00KG03979.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9703846674184914
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
