id: I2F1C9193
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T00:29:38+00:00'
last_modified: '2022-06-15T18:23:38.000056+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03976
  title: གསུང་འབུམ། འཇིགས་མེད་ཕུན་ཚོགས་འབྱུང་གནས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E3FB:
      image_group_id: I00KG03978
      title: Volume 1 of gsung 'bum/_'jigs med phun tshogs 'byung gnas
      total_pages: 175
      order: 1
      base_file: E3FB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
